### ISSUE TITLE
Doesn't work with html loader

### ISSUE THREAD

**Issue by bpinto** [WealthBar/slm-loader#6]
Everything was working with:

```
      {
        test: /\.slm$/,
        exclude: /(node_modules)/,
        loaders: ["ng-cache?prefix=app/assets/templates:**&name=[name]", "slm"]
      },
```

but once I added the `html-loader`:
```
      {
        test: /\.slm$/,
        exclude: /(node_modules)/,
        loaders: ["ng-cache?prefix=app/assets/templates:**&name=[name]", "html", "slm"]
      },
```

everything started to fail:
```
Error: Parse Error: <ul class=\"errors-list\" ng-messages=\"validation.model.$error\"><li ng-message=\"{{::validation.name}}\"><span ng-transclude=\"\"></span></li></ul>";
```

do you have any idea?

**Comment by chrisnicola** [comment]
No that seems quite odd. Html loader recently changed how it works significantly though and it doesn't just output a simple string anymore but outputs a module. I would test without "SLM" and just use and HTML file output and see if you have the same problems.

**Comment by bpinto** [comment]
I think you are right. The error doesn't seem to be here. 👍
